#!/usr/bin/env bash
#
# based on github/getmicah & onodera-punpun

source /home/dt/bin/lemonbar/colours

groups() {
    ico="þ "
    cur=`xdotool get_desktop`
    tot=4
    for i in 0 1 2 3; do
      if [ $i -eq $cur ]
      then
		line="${line}\ue000"
        #line="${line}%{F$COLOUR_HL2}\ue000 %{F-}"
      else
        line="${line}%{A:xdotool set_desktop $i:}\ue001%{A}"
      fi
    done
    echo -e "%{F$COLOUR_FG1}$line"
}

window() {
  win=`xtitle -t 42`
  echo -e " %{A:skippy-xd --activate-window-picker:}%{B$COLOUR_BG1}$p\ue0b9 $win%{A}"
}

music() {
  cur=`mpc`
  song=`mpc current`
  nex="%{A:mpc -q next:}\ue09d %{A}"
  click="%{A:mpc -q toggle:}%{A2:termite -e ncmpcpp:}%{A3:mpc -q stop:}%{A4:mpc -q volume +5:}%{A5:mpc -q volume -5:}"
  clickend="%{A}%{A}%{A}%{A}%{A}"
  if [[ $cur == *"playing"* ]]
  then
    mus="\ue0fe";
  elif [[ $cur == *"paused"* ]]
  then
    mus="\ue09b"
  else
    mus="\ue099"
  fi
  echo -e "$click$mus$clickend"
}


tray() {
  pidof  tint2 >/dev/null
  if [[ $? -ne 0 ]] ; then
          echo -e "%{A:tint2 -c /home/dt/bin/lemonbar/tint2_bar&:}\ue195%{A}"
        else
          echo -e "%{A:killall tint2:}\ue193%{A}"
  fi
}

volume() {
    echo -e "%{A:pavucontrol&:}\ue094%{A}"
}

clock() {
    date=`date '+%I:%M %p'`
    echo -e "%{A:gsimplecal&:}$date%{A}"
}


pacheck() {
    echo -e "%{A:termite -e yaourt -Syua&& kill:}\ue14d%{A}"
}

launcher() {
    echo -e "%{A:/home/dt/bin/lemonbar/obpanelmenu.sh:}%{F$COLOUR_BG1}%{B$COLOUR_FG2} \ue1f1 %{F-}%{B-}%{A}"
}


#scroll start/end
SS="%{A4:/home/dt/bin/lemonbar/scrollup:}%{A5:/home/dt/bin/lemonbar/scrolldn:}"
SE="%{A}%{A}"

while :; do
    p=""
    l="$SS$(groups) %{B$COLOUR_BG1}%{F$COLOUR_FG1}$(window)%{F-}$SE"
    c="$SS $p $(clock)$SE"
    r=" $(volume)$(music)"
    echo "%{l}%{B$COLOUR_BG2}  $l$p%{c}$c%{r}%{B$COLOUR_BG2}$p $r%{B$COLOUR_BG1}"
    sleep 0.25
done |

lemonbar -a 32 -g "1680x24+32" -f "$FONT1" -f "$FONT2" -F "$COLOUR_FG1" -B "$COLOUR_BG1" | sh &
tint2 -c /home/dt/bin/lemonbar/tintLeft &  
tint2 -c /home/dt/bin/lemonbar/tintRight &

