#!/bin/bash

cur=`xdotool get_desktop`

if [ $cur -eq 0 ]
then
  xdotool set_desktop 3
elif [ $cur -eq 1 ]
then
  xdotool set_desktop 0
elif [ $cur -eq 2 ]
then
  xdotool set_desktop 1
elif [ $cur -eq 3 ]
then
  xdotool set_desktop 2
fi
